name: (Auto) Merge PR to 'next' branch

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Previously closed PR number (required for manual run)'
        required: true
      pr_title:
        description: 'PR title (optional, for manual run)'
        required: false

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  create-pr-to-next:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: [worker-small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set PR variables
        id: pr_vars
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "pr_number=${{ github.event.inputs.pr_number }}" >> $GITHUB_OUTPUT
            echo "pr_title=${{ github.event.inputs.pr_title }}" >> $GITHUB_OUTPUT
          else
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "pr_title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          fi

      - name: Get squashed commit SHA
        id: get_squashed_commit
        run: |
          git fetch origin main
          SQUASHED_COMMIT_SHA=$(git rev-parse origin/main)
          echo "Squashed commit SHA: $SQUASHED_COMMIT_SHA"
          echo "PR Number: ${{ steps.pr_vars.outputs.pr_number }}"
          echo "PR Title: ${{ steps.pr_vars.outputs.pr_title }}"
          echo "squashed_commit=$SQUASHED_COMMIT_SHA" >> $GITHUB_OUTPUT

      - name: Create branch for PR
        id: create_branch
        run: |
          git fetch origin next
          git checkout origin/next
          BRANCH_NAME="auto-to-next/pr-${{ steps.pr_vars.outputs.pr_number }}"
          git checkout -b $BRANCH_NAME
          echo "Created branch '$BRANCH_NAME' based on 'next'"
          git cherry-pick ${{ steps.get_squashed_commit.outputs.squashed_commit }}
          git push origin $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Prepare body for PR
        run: |
          echo "This PR contains only the changes from PR #${{ steps.pr_vars.outputs.pr_number }} that was merged to main." > pr_body.txt
          echo "" >> pr_body.txt
          echo "Original PR: #${{ steps.pr_vars.outputs.pr_number }}" >> pr_body.txt
          echo "Original Title: ${{ steps.pr_vars.outputs.pr_title }}" >> pr_body.txt
          echo "" >> pr_body.txt
          echo "This is an automated PR created by the GitHub Actions workflow." >> pr_body.txt

      - name: Create Pull Request
        run: |
          gh pr create --base next --head ${{ steps.create_branch.outputs.branch_name }} \
            --title "[Auto PR #${{ steps.pr_vars.outputs.pr_number }} to next] ${{ steps.pr_vars.outputs.pr_title }}" \
            --body-file pr_body.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger verification
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: verify_auto_pr
          client-payload: |
            {
              "pr_number": "${{ steps.pr_vars.outputs.pr_number }}",
              "commit_sha": "${{ steps.get_squashed_commit.outputs.squashed_commit }}"
            }

      - name: List PRs
        run: gh pr list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
